[versions]
agp = "8.9.2"
datastore = "1.1.4"
firebaseBom = "33.13.0"
firebasePlugin = "4.4.2"
firebaseCrashPlugin = "3.0.3"
koinAndroid = "4.0.4"
koinAnnotatinos = "1.4.0"
kotlin = "2.1.20"
coreKtx = "1.16.0"
kotlinxSerializationJson = "1.8.0"
kotlinxSerializationJsonPlugin = "2.1.20"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2025.04.01"
ksp = "2.1.20-2.0.0"
ktor = "3.1.1"
chucker = "4.0.0"
navigationCompose = "2.8.9"
protobufJavalite = "3.25.5"
room = "2.7.1"
secretsGradlePlugin = "2.0.1"
protobufPlugin = "0.9.4"
workManager = "2.10.1"
workStartup = "1.2.0"
lottieCompose = "6.4.1"
widget = "1.1.1"
vico = "2.1.2"

#build constants
applicationId = "mega.triple.aaa"
minSdk = "24"
targetSdk = "35"
compileSdk = "35"
javaVersion = "17"
versionCode = "2"
versionName = "0.0.2"
kotlinCompilerExtensionVersion = "1.5.1"
#projects
projectDataNetwork = ":data-network"
projectDataProto = ":data-proto"
projectDataPreference = ":data-preference"
projectDataLocal = ":data-local"
projectDomain = ":domain"
projectCoreCommon = ":core-common"
projectCoreUi = ":core-ui"
projectCoreStrings = ":core-strings"
projectCoreNavigation = ":core-navigation"
projectFeatureMain = ":feature-main"
projectFeatureHome = ":feature-home"
projectFeatureSearch = ":feature-search"
projectFeatureSettings = ":feature-settings"
projectFeatureSync = ":feature-sync"
projectFeatureWidget = ":feature-widget"

[libraries]
# Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# Build logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
secrets-gradle-plugin = { group = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", name = "secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
ksp-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

# Widget
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "widget" }
androidx-glance-appwidget-preview = { module = "androidx.glance:glance-appwidget-preview", version.ref = "widget" }
androidx-glance-preview = { module = "androidx.glance:glance-preview", version.ref = "widget" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "widget" }
androidx-glance-material = { module = "androidx.glance:glance-material", version.ref = "widget" }

# Koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-androidx-worker = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koinAndroid" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroid" }
koin-annotatinos = { module = "io.insert-koin:koin-annotations", version.ref = "koinAnnotatinos" }
koin-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinAnnotatinos" }

# Network
io-ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
io-ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
io-ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
io-ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }

#WorkManager
worker-lib = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
worker-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "workStartup" }

# 3d party
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufJavalite" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottieCompose" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }

# Line chart
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinxSerializationJsonPlugin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }

firebase = { id = "com.google.gms.google-services", version.ref = "firebasePlugin" }
firebase-crashlytic = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashPlugin" }

[bundles]
network = [
    "io-ktor-client-core",
    "io-ktor-client-okhttp",
    "io-ktor-client-content-negotiation",
    "io-ktor-serialization-json",
    "kotlinx-serialization-json",
    "chucker",
]
widget = [
    "androidx-glance-appwidget",
    "androidx-glance-appwidget-preview",
    "androidx-glance-preview",
    "androidx-glance-material3",
    "androidx-glance-material",
]
